ShopOLX/Controllers/LikeController.cs
using DataAccess.Data;
using DataAccess.Data.Entities;
using DataAccess.Migrations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using ShopOLX.Helpers;
using System.Runtime.Intrinsics.Arm;
using System.Security.Claims;

namespace ShopOLX.Controllers
{
    public class LikeController : Controller
    {
        private readonly ShopDbContext ctx;
        private string CurrentUserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

        public LikeController(ShopDbContext ctx)
        {
            this.ctx = ctx;
        }

        public async Task<IActionResult> AddFavorite(int id)
        {
            if (id == 0)
            {
                return Redirect("../Index");
            }
            var user = await ctx.Users.FirstOrDefaultAsync(t => t.Id == CurrentUserId);
            if (user == null)
            {
                return Redirect("../Index");
            }
            var product = await ctx.Products.FirstOrDefaultAsync(t => t.Id ==  id);
            var favorite = new Favorite
            {
                UserId = user.Id,
                Products = new List<Product> { product },
                Date = DateTime.UtcNow,
            };
            await ctx.Set<Favorite>().AddAsync(favorite);
            await ctx.SaveChangesAsync();
            return Redirect("../Index");
        }

        public async Task<IActionResult> Index()
        {
            var result = await ctx.Users
                .Where(t => t.Id == CurrentUserId)
                .Include(t => t.Favorites)
                .ThenInclude(t => t.Products)
                .SelectMany(t => t.Favorites)
                .SelectMany(t => t.Products)
                .AsNoTracking()
                .ToListAsync();
            return View(result);
        }

        public async Task<IActionResult> UnLike(int id)
        {
            if (id == 0)
            {
                return Redirect("../Index");
            }

            var user = await ctx.Users.FirstOrDefaultAsync(t => t.Id == CurrentUserId);

            if (user == null)
            {
                return Redirect("../Index");
            }

            var favorite = await ctx.Favorites
                .Include(f => f.Products)
                .Where(f => f.UserId == CurrentUserId)
                .FirstOrDefaultAsync();

            if (favorite != null)
            {
                var productToRemove = favorite.Products.FirstOrDefault(p => p.Id == id);

                if (productToRemove != null)
                {
                    favorite.Products.Remove(productToRemove);
                    await ctx.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }
    }
}

ShopOLX/Controllers/ProductController.cs
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ShopOLX.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly ShopDbContext ctx;
        public ProductController(ShopDbContext ctx)
        {
            this.ctx = ctx;
        }

        private void LoadCategories()
        {
            this.ViewBag.Categories = new SelectList(ctx.Categories.ToList(), "Id", "Name");
        }

        public IActionResult Index()
        {
            var products = ctx.Products.ToList();

            return View(products);
        }

        public IActionResult Delete(int id)
        {
            var item = ctx.Products.Find(id);

            if (item == null) return NotFound();

            ctx.Products.Remove(item);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            LoadCategories();
            
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product prod)
        {
            if (!ModelState.IsValid)
            {
                LoadCategories();
                return View(prod);
            }

            ctx.Products.Add(prod);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var item = ctx.Products.Find(id);

            if (item == null) return NotFound();

            LoadCategories();

            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Product prod)
        {
            if (!ModelState.IsValid)
            {
                LoadCategories();
                return View(prod);
            }

            ctx.Products.Update(prod);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Show(int id)
        {
            var item = ctx.Products.Find(id);

            if (item == null) return NotFound();

            ViewBag.Message = item;
            
            return View("ShowProduct");
        }
    }
}

ShopOLX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ShopOLX - @ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="./images/favicon.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopOLX.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopOLX</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Like" asp-action="Index">Liked</a>
                        </li>
                        @if (User.IsInRole(Roles.Admin.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ShopOLX - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>